// Generated by gencpp from file trajecgenerator/addCrSplineTrajecHandlerRequest.msg
// DO NOT EDIT!


#ifndef TRAJECGENERATOR_MESSAGE_ADDCRSPLINETRAJECHANDLERREQUEST_H
#define TRAJECGENERATOR_MESSAGE_ADDCRSPLINETRAJECHANDLERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace trajecgenerator
{
template <class ContainerAllocator>
struct addCrSplineTrajecHandlerRequest_
{
  typedef addCrSplineTrajecHandlerRequest_<ContainerAllocator> Type;

  addCrSplineTrajecHandlerRequest_()
    : name()
    , pointsX()
    , pointsY()
    , closed(false)
    , time(0.0)
    , k(0.0)  {
    }
  addCrSplineTrajecHandlerRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , pointsX(_alloc)
    , pointsY(_alloc)
    , closed(false)
    , time(0.0)
    , k(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _pointsX_type;
  _pointsX_type pointsX;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _pointsY_type;
  _pointsY_type pointsY;

   typedef uint8_t _closed_type;
  _closed_type closed;

   typedef float _time_type;
  _time_type time;

   typedef float _k_type;
  _k_type k;





  typedef boost::shared_ptr< ::trajecgenerator::addCrSplineTrajecHandlerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::trajecgenerator::addCrSplineTrajecHandlerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct addCrSplineTrajecHandlerRequest_

typedef ::trajecgenerator::addCrSplineTrajecHandlerRequest_<std::allocator<void> > addCrSplineTrajecHandlerRequest;

typedef boost::shared_ptr< ::trajecgenerator::addCrSplineTrajecHandlerRequest > addCrSplineTrajecHandlerRequestPtr;
typedef boost::shared_ptr< ::trajecgenerator::addCrSplineTrajecHandlerRequest const> addCrSplineTrajecHandlerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::trajecgenerator::addCrSplineTrajecHandlerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::trajecgenerator::addCrSplineTrajecHandlerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::trajecgenerator::addCrSplineTrajecHandlerRequest_<ContainerAllocator1> & lhs, const ::trajecgenerator::addCrSplineTrajecHandlerRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.pointsX == rhs.pointsX &&
    lhs.pointsY == rhs.pointsY &&
    lhs.closed == rhs.closed &&
    lhs.time == rhs.time &&
    lhs.k == rhs.k;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::trajecgenerator::addCrSplineTrajecHandlerRequest_<ContainerAllocator1> & lhs, const ::trajecgenerator::addCrSplineTrajecHandlerRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace trajecgenerator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::trajecgenerator::addCrSplineTrajecHandlerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trajecgenerator::addCrSplineTrajecHandlerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trajecgenerator::addCrSplineTrajecHandlerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trajecgenerator::addCrSplineTrajecHandlerRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trajecgenerator::addCrSplineTrajecHandlerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trajecgenerator::addCrSplineTrajecHandlerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::trajecgenerator::addCrSplineTrajecHandlerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a67c4c6881252e2b649960aef205c15e";
  }

  static const char* value(const ::trajecgenerator::addCrSplineTrajecHandlerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa67c4c6881252e2bULL;
  static const uint64_t static_value2 = 0x649960aef205c15eULL;
};

template<class ContainerAllocator>
struct DataType< ::trajecgenerator::addCrSplineTrajecHandlerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trajecgenerator/addCrSplineTrajecHandlerRequest";
  }

  static const char* value(const ::trajecgenerator::addCrSplineTrajecHandlerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::trajecgenerator::addCrSplineTrajecHandlerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"float32[] pointsX\n"
"float32[] pointsY\n"
"bool closed\n"
"float32 time\n"
"float32 k\n"
;
  }

  static const char* value(const ::trajecgenerator::addCrSplineTrajecHandlerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::trajecgenerator::addCrSplineTrajecHandlerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.pointsX);
      stream.next(m.pointsY);
      stream.next(m.closed);
      stream.next(m.time);
      stream.next(m.k);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct addCrSplineTrajecHandlerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::trajecgenerator::addCrSplineTrajecHandlerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::trajecgenerator::addCrSplineTrajecHandlerRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "pointsX[]" << std::endl;
    for (size_t i = 0; i < v.pointsX.size(); ++i)
    {
      s << indent << "  pointsX[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pointsX[i]);
    }
    s << indent << "pointsY[]" << std::endl;
    for (size_t i = 0; i < v.pointsY.size(); ++i)
    {
      s << indent << "  pointsY[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pointsY[i]);
    }
    s << indent << "closed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.closed);
    s << indent << "time: ";
    Printer<float>::stream(s, indent + "  ", v.time);
    s << indent << "k: ";
    Printer<float>::stream(s, indent + "  ", v.k);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAJECGENERATOR_MESSAGE_ADDCRSPLINETRAJECHANDLERREQUEST_H
