// Generated by gencpp from file trajecgenerator/addCircleTrajecHandler.msg
// DO NOT EDIT!


#ifndef TRAJECGENERATOR_MESSAGE_ADDCIRCLETRAJECHANDLER_H
#define TRAJECGENERATOR_MESSAGE_ADDCIRCLETRAJECHANDLER_H

#include <ros/service_traits.h>


#include <trajecgenerator/addCircleTrajecHandlerRequest.h>
#include <trajecgenerator/addCircleTrajecHandlerResponse.h>


namespace trajecgenerator
{

struct addCircleTrajecHandler
{

typedef addCircleTrajecHandlerRequest Request;
typedef addCircleTrajecHandlerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct addCircleTrajecHandler
} // namespace trajecgenerator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::trajecgenerator::addCircleTrajecHandler > {
  static const char* value()
  {
    return "4a4faaf714cc18070417071d78411d73";
  }

  static const char* value(const ::trajecgenerator::addCircleTrajecHandler&) { return value(); }
};

template<>
struct DataType< ::trajecgenerator::addCircleTrajecHandler > {
  static const char* value()
  {
    return "trajecgenerator/addCircleTrajecHandler";
  }

  static const char* value(const ::trajecgenerator::addCircleTrajecHandler&) { return value(); }
};


// service_traits::MD5Sum< ::trajecgenerator::addCircleTrajecHandlerRequest> should match
// service_traits::MD5Sum< ::trajecgenerator::addCircleTrajecHandler >
template<>
struct MD5Sum< ::trajecgenerator::addCircleTrajecHandlerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::trajecgenerator::addCircleTrajecHandler >::value();
  }
  static const char* value(const ::trajecgenerator::addCircleTrajecHandlerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::trajecgenerator::addCircleTrajecHandlerRequest> should match
// service_traits::DataType< ::trajecgenerator::addCircleTrajecHandler >
template<>
struct DataType< ::trajecgenerator::addCircleTrajecHandlerRequest>
{
  static const char* value()
  {
    return DataType< ::trajecgenerator::addCircleTrajecHandler >::value();
  }
  static const char* value(const ::trajecgenerator::addCircleTrajecHandlerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::trajecgenerator::addCircleTrajecHandlerResponse> should match
// service_traits::MD5Sum< ::trajecgenerator::addCircleTrajecHandler >
template<>
struct MD5Sum< ::trajecgenerator::addCircleTrajecHandlerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::trajecgenerator::addCircleTrajecHandler >::value();
  }
  static const char* value(const ::trajecgenerator::addCircleTrajecHandlerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::trajecgenerator::addCircleTrajecHandlerResponse> should match
// service_traits::DataType< ::trajecgenerator::addCircleTrajecHandler >
template<>
struct DataType< ::trajecgenerator::addCircleTrajecHandlerResponse>
{
  static const char* value()
  {
    return DataType< ::trajecgenerator::addCircleTrajecHandler >::value();
  }
  static const char* value(const ::trajecgenerator::addCircleTrajecHandlerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAJECGENERATOR_MESSAGE_ADDCIRCLETRAJECHANDLER_H
