// Generated by gencpp from file trajecgenerator/addCrSplineTrajecHandler.msg
// DO NOT EDIT!


#ifndef TRAJECGENERATOR_MESSAGE_ADDCRSPLINETRAJECHANDLER_H
#define TRAJECGENERATOR_MESSAGE_ADDCRSPLINETRAJECHANDLER_H

#include <ros/service_traits.h>


#include <trajecgenerator/addCrSplineTrajecHandlerRequest.h>
#include <trajecgenerator/addCrSplineTrajecHandlerResponse.h>


namespace trajecgenerator
{

struct addCrSplineTrajecHandler
{

typedef addCrSplineTrajecHandlerRequest Request;
typedef addCrSplineTrajecHandlerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct addCrSplineTrajecHandler
} // namespace trajecgenerator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::trajecgenerator::addCrSplineTrajecHandler > {
  static const char* value()
  {
    return "a67c4c6881252e2b649960aef205c15e";
  }

  static const char* value(const ::trajecgenerator::addCrSplineTrajecHandler&) { return value(); }
};

template<>
struct DataType< ::trajecgenerator::addCrSplineTrajecHandler > {
  static const char* value()
  {
    return "trajecgenerator/addCrSplineTrajecHandler";
  }

  static const char* value(const ::trajecgenerator::addCrSplineTrajecHandler&) { return value(); }
};


// service_traits::MD5Sum< ::trajecgenerator::addCrSplineTrajecHandlerRequest> should match
// service_traits::MD5Sum< ::trajecgenerator::addCrSplineTrajecHandler >
template<>
struct MD5Sum< ::trajecgenerator::addCrSplineTrajecHandlerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::trajecgenerator::addCrSplineTrajecHandler >::value();
  }
  static const char* value(const ::trajecgenerator::addCrSplineTrajecHandlerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::trajecgenerator::addCrSplineTrajecHandlerRequest> should match
// service_traits::DataType< ::trajecgenerator::addCrSplineTrajecHandler >
template<>
struct DataType< ::trajecgenerator::addCrSplineTrajecHandlerRequest>
{
  static const char* value()
  {
    return DataType< ::trajecgenerator::addCrSplineTrajecHandler >::value();
  }
  static const char* value(const ::trajecgenerator::addCrSplineTrajecHandlerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::trajecgenerator::addCrSplineTrajecHandlerResponse> should match
// service_traits::MD5Sum< ::trajecgenerator::addCrSplineTrajecHandler >
template<>
struct MD5Sum< ::trajecgenerator::addCrSplineTrajecHandlerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::trajecgenerator::addCrSplineTrajecHandler >::value();
  }
  static const char* value(const ::trajecgenerator::addCrSplineTrajecHandlerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::trajecgenerator::addCrSplineTrajecHandlerResponse> should match
// service_traits::DataType< ::trajecgenerator::addCrSplineTrajecHandler >
template<>
struct DataType< ::trajecgenerator::addCrSplineTrajecHandlerResponse>
{
  static const char* value()
  {
    return DataType< ::trajecgenerator::addCrSplineTrajecHandler >::value();
  }
  static const char* value(const ::trajecgenerator::addCrSplineTrajecHandlerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAJECGENERATOR_MESSAGE_ADDCRSPLINETRAJECHANDLER_H
