// Generated by gencpp from file trajecgenerator/boolRequestRequest.msg
// DO NOT EDIT!


#ifndef TRAJECGENERATOR_MESSAGE_BOOLREQUESTREQUEST_H
#define TRAJECGENERATOR_MESSAGE_BOOLREQUESTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace trajecgenerator
{
template <class ContainerAllocator>
struct boolRequestRequest_
{
  typedef boolRequestRequest_<ContainerAllocator> Type;

  boolRequestRequest_()
    : b(false)  {
    }
  boolRequestRequest_(const ContainerAllocator& _alloc)
    : b(false)  {
  (void)_alloc;
    }



   typedef uint8_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::trajecgenerator::boolRequestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::trajecgenerator::boolRequestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct boolRequestRequest_

typedef ::trajecgenerator::boolRequestRequest_<std::allocator<void> > boolRequestRequest;

typedef boost::shared_ptr< ::trajecgenerator::boolRequestRequest > boolRequestRequestPtr;
typedef boost::shared_ptr< ::trajecgenerator::boolRequestRequest const> boolRequestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::trajecgenerator::boolRequestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::trajecgenerator::boolRequestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::trajecgenerator::boolRequestRequest_<ContainerAllocator1> & lhs, const ::trajecgenerator::boolRequestRequest_<ContainerAllocator2> & rhs)
{
  return lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::trajecgenerator::boolRequestRequest_<ContainerAllocator1> & lhs, const ::trajecgenerator::boolRequestRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace trajecgenerator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::trajecgenerator::boolRequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trajecgenerator::boolRequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trajecgenerator::boolRequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trajecgenerator::boolRequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trajecgenerator::boolRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trajecgenerator::boolRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::trajecgenerator::boolRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88c93a4e354c9b18b18fde29f72f94c2";
  }

  static const char* value(const ::trajecgenerator::boolRequestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88c93a4e354c9b18ULL;
  static const uint64_t static_value2 = 0xb18fde29f72f94c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::trajecgenerator::boolRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trajecgenerator/boolRequestRequest";
  }

  static const char* value(const ::trajecgenerator::boolRequestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::trajecgenerator::boolRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool b\n"
;
  }

  static const char* value(const ::trajecgenerator::boolRequestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::trajecgenerator::boolRequestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct boolRequestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::trajecgenerator::boolRequestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::trajecgenerator::boolRequestRequest_<ContainerAllocator>& v)
  {
    s << indent << "b: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAJECGENERATOR_MESSAGE_BOOLREQUESTREQUEST_H
