// Generated by gencpp from file trajecgenerator/float32RequestRequest.msg
// DO NOT EDIT!


#ifndef TRAJECGENERATOR_MESSAGE_FLOAT32REQUESTREQUEST_H
#define TRAJECGENERATOR_MESSAGE_FLOAT32REQUESTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace trajecgenerator
{
template <class ContainerAllocator>
struct float32RequestRequest_
{
  typedef float32RequestRequest_<ContainerAllocator> Type;

  float32RequestRequest_()
    : f(0.0)  {
    }
  float32RequestRequest_(const ContainerAllocator& _alloc)
    : f(0.0)  {
  (void)_alloc;
    }



   typedef float _f_type;
  _f_type f;





  typedef boost::shared_ptr< ::trajecgenerator::float32RequestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::trajecgenerator::float32RequestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct float32RequestRequest_

typedef ::trajecgenerator::float32RequestRequest_<std::allocator<void> > float32RequestRequest;

typedef boost::shared_ptr< ::trajecgenerator::float32RequestRequest > float32RequestRequestPtr;
typedef boost::shared_ptr< ::trajecgenerator::float32RequestRequest const> float32RequestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::trajecgenerator::float32RequestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::trajecgenerator::float32RequestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::trajecgenerator::float32RequestRequest_<ContainerAllocator1> & lhs, const ::trajecgenerator::float32RequestRequest_<ContainerAllocator2> & rhs)
{
  return lhs.f == rhs.f;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::trajecgenerator::float32RequestRequest_<ContainerAllocator1> & lhs, const ::trajecgenerator::float32RequestRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace trajecgenerator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::trajecgenerator::float32RequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trajecgenerator::float32RequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trajecgenerator::float32RequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trajecgenerator::float32RequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trajecgenerator::float32RequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trajecgenerator::float32RequestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::trajecgenerator::float32RequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29e3b508ca3c2e2afe7cfe66d63c0a51";
  }

  static const char* value(const ::trajecgenerator::float32RequestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29e3b508ca3c2e2aULL;
  static const uint64_t static_value2 = 0xfe7cfe66d63c0a51ULL;
};

template<class ContainerAllocator>
struct DataType< ::trajecgenerator::float32RequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trajecgenerator/float32RequestRequest";
  }

  static const char* value(const ::trajecgenerator::float32RequestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::trajecgenerator::float32RequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 f\n"
;
  }

  static const char* value(const ::trajecgenerator::float32RequestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::trajecgenerator::float32RequestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.f);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct float32RequestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::trajecgenerator::float32RequestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::trajecgenerator::float32RequestRequest_<ContainerAllocator>& v)
  {
    s << indent << "f: ";
    Printer<float>::stream(s, indent + "  ", v.f);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRAJECGENERATOR_MESSAGE_FLOAT32REQUESTREQUEST_H
