// Generated by gencpp from file trajecgenerator/float32Request.msg
// DO NOT EDIT!


#ifndef TRAJECGENERATOR_MESSAGE_FLOAT32REQUEST_H
#define TRAJECGENERATOR_MESSAGE_FLOAT32REQUEST_H

#include <ros/service_traits.h>


#include <trajecgenerator/float32RequestRequest.h>
#include <trajecgenerator/float32RequestResponse.h>


namespace trajecgenerator
{

struct float32Request
{

typedef float32RequestRequest Request;
typedef float32RequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct float32Request
} // namespace trajecgenerator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::trajecgenerator::float32Request > {
  static const char* value()
  {
    return "29e3b508ca3c2e2afe7cfe66d63c0a51";
  }

  static const char* value(const ::trajecgenerator::float32Request&) { return value(); }
};

template<>
struct DataType< ::trajecgenerator::float32Request > {
  static const char* value()
  {
    return "trajecgenerator/float32Request";
  }

  static const char* value(const ::trajecgenerator::float32Request&) { return value(); }
};


// service_traits::MD5Sum< ::trajecgenerator::float32RequestRequest> should match
// service_traits::MD5Sum< ::trajecgenerator::float32Request >
template<>
struct MD5Sum< ::trajecgenerator::float32RequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::trajecgenerator::float32Request >::value();
  }
  static const char* value(const ::trajecgenerator::float32RequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::trajecgenerator::float32RequestRequest> should match
// service_traits::DataType< ::trajecgenerator::float32Request >
template<>
struct DataType< ::trajecgenerator::float32RequestRequest>
{
  static const char* value()
  {
    return DataType< ::trajecgenerator::float32Request >::value();
  }
  static const char* value(const ::trajecgenerator::float32RequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::trajecgenerator::float32RequestResponse> should match
// service_traits::MD5Sum< ::trajecgenerator::float32Request >
template<>
struct MD5Sum< ::trajecgenerator::float32RequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::trajecgenerator::float32Request >::value();
  }
  static const char* value(const ::trajecgenerator::float32RequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::trajecgenerator::float32RequestResponse> should match
// service_traits::DataType< ::trajecgenerator::float32Request >
template<>
struct DataType< ::trajecgenerator::float32RequestResponse>
{
  static const char* value()
  {
    return DataType< ::trajecgenerator::float32Request >::value();
  }
  static const char* value(const ::trajecgenerator::float32RequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAJECGENERATOR_MESSAGE_FLOAT32REQUEST_H
