// Generated by gencpp from file trajecgenerator/plotTrajectory.msg
// DO NOT EDIT!


#ifndef TRAJECGENERATOR_MESSAGE_PLOTTRAJECTORY_H
#define TRAJECGENERATOR_MESSAGE_PLOTTRAJECTORY_H

#include <ros/service_traits.h>


#include <trajecgenerator/plotTrajectoryRequest.h>
#include <trajecgenerator/plotTrajectoryResponse.h>


namespace trajecgenerator
{

struct plotTrajectory
{

typedef plotTrajectoryRequest Request;
typedef plotTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct plotTrajectory
} // namespace trajecgenerator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::trajecgenerator::plotTrajectory > {
  static const char* value()
  {
    return "2860cf7d8312d3024b3ab61f13528c56";
  }

  static const char* value(const ::trajecgenerator::plotTrajectory&) { return value(); }
};

template<>
struct DataType< ::trajecgenerator::plotTrajectory > {
  static const char* value()
  {
    return "trajecgenerator/plotTrajectory";
  }

  static const char* value(const ::trajecgenerator::plotTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::trajecgenerator::plotTrajectoryRequest> should match
// service_traits::MD5Sum< ::trajecgenerator::plotTrajectory >
template<>
struct MD5Sum< ::trajecgenerator::plotTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::trajecgenerator::plotTrajectory >::value();
  }
  static const char* value(const ::trajecgenerator::plotTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::trajecgenerator::plotTrajectoryRequest> should match
// service_traits::DataType< ::trajecgenerator::plotTrajectory >
template<>
struct DataType< ::trajecgenerator::plotTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::trajecgenerator::plotTrajectory >::value();
  }
  static const char* value(const ::trajecgenerator::plotTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::trajecgenerator::plotTrajectoryResponse> should match
// service_traits::MD5Sum< ::trajecgenerator::plotTrajectory >
template<>
struct MD5Sum< ::trajecgenerator::plotTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::trajecgenerator::plotTrajectory >::value();
  }
  static const char* value(const ::trajecgenerator::plotTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::trajecgenerator::plotTrajectoryResponse> should match
// service_traits::DataType< ::trajecgenerator::plotTrajectory >
template<>
struct DataType< ::trajecgenerator::plotTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::trajecgenerator::plotTrajectory >::value();
  }
  static const char* value(const ::trajecgenerator::plotTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAJECGENERATOR_MESSAGE_PLOTTRAJECTORY_H
