// Generated by gencpp from file trajecgenerator/removeTrajecHandler.msg
// DO NOT EDIT!


#ifndef TRAJECGENERATOR_MESSAGE_REMOVETRAJECHANDLER_H
#define TRAJECGENERATOR_MESSAGE_REMOVETRAJECHANDLER_H

#include <ros/service_traits.h>


#include <trajecgenerator/removeTrajecHandlerRequest.h>
#include <trajecgenerator/removeTrajecHandlerResponse.h>


namespace trajecgenerator
{

struct removeTrajecHandler
{

typedef removeTrajecHandlerRequest Request;
typedef removeTrajecHandlerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct removeTrajecHandler
} // namespace trajecgenerator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::trajecgenerator::removeTrajecHandler > {
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::trajecgenerator::removeTrajecHandler&) { return value(); }
};

template<>
struct DataType< ::trajecgenerator::removeTrajecHandler > {
  static const char* value()
  {
    return "trajecgenerator/removeTrajecHandler";
  }

  static const char* value(const ::trajecgenerator::removeTrajecHandler&) { return value(); }
};


// service_traits::MD5Sum< ::trajecgenerator::removeTrajecHandlerRequest> should match
// service_traits::MD5Sum< ::trajecgenerator::removeTrajecHandler >
template<>
struct MD5Sum< ::trajecgenerator::removeTrajecHandlerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::trajecgenerator::removeTrajecHandler >::value();
  }
  static const char* value(const ::trajecgenerator::removeTrajecHandlerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::trajecgenerator::removeTrajecHandlerRequest> should match
// service_traits::DataType< ::trajecgenerator::removeTrajecHandler >
template<>
struct DataType< ::trajecgenerator::removeTrajecHandlerRequest>
{
  static const char* value()
  {
    return DataType< ::trajecgenerator::removeTrajecHandler >::value();
  }
  static const char* value(const ::trajecgenerator::removeTrajecHandlerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::trajecgenerator::removeTrajecHandlerResponse> should match
// service_traits::MD5Sum< ::trajecgenerator::removeTrajecHandler >
template<>
struct MD5Sum< ::trajecgenerator::removeTrajecHandlerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::trajecgenerator::removeTrajecHandler >::value();
  }
  static const char* value(const ::trajecgenerator::removeTrajecHandlerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::trajecgenerator::removeTrajecHandlerResponse> should match
// service_traits::DataType< ::trajecgenerator::removeTrajecHandler >
template<>
struct DataType< ::trajecgenerator::removeTrajecHandlerResponse>
{
  static const char* value()
  {
    return DataType< ::trajecgenerator::removeTrajecHandler >::value();
  }
  static const char* value(const ::trajecgenerator::removeTrajecHandlerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TRAJECGENERATOR_MESSAGE_REMOVETRAJECHANDLER_H
