// Generated by gencpp from file trajecgenerator/removeTrajecHandlerResponse.msg
// DO NOT EDIT!


#ifndef TRAJECGENERATOR_MESSAGE_REMOVETRAJECHANDLERRESPONSE_H
#define TRAJECGENERATOR_MESSAGE_REMOVETRAJECHANDLERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace trajecgenerator
{
template <class ContainerAllocator>
struct removeTrajecHandlerResponse_
{
  typedef removeTrajecHandlerResponse_<ContainerAllocator> Type;

  removeTrajecHandlerResponse_()
    {
    }
  removeTrajecHandlerResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::trajecgenerator::removeTrajecHandlerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::trajecgenerator::removeTrajecHandlerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct removeTrajecHandlerResponse_

typedef ::trajecgenerator::removeTrajecHandlerResponse_<std::allocator<void> > removeTrajecHandlerResponse;

typedef boost::shared_ptr< ::trajecgenerator::removeTrajecHandlerResponse > removeTrajecHandlerResponsePtr;
typedef boost::shared_ptr< ::trajecgenerator::removeTrajecHandlerResponse const> removeTrajecHandlerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::trajecgenerator::removeTrajecHandlerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::trajecgenerator::removeTrajecHandlerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace trajecgenerator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::trajecgenerator::removeTrajecHandlerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trajecgenerator::removeTrajecHandlerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trajecgenerator::removeTrajecHandlerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trajecgenerator::removeTrajecHandlerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trajecgenerator::removeTrajecHandlerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trajecgenerator::removeTrajecHandlerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::trajecgenerator::removeTrajecHandlerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::trajecgenerator::removeTrajecHandlerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::trajecgenerator::removeTrajecHandlerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trajecgenerator/removeTrajecHandlerResponse";
  }

  static const char* value(const ::trajecgenerator::removeTrajecHandlerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::trajecgenerator::removeTrajecHandlerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::trajecgenerator::removeTrajecHandlerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::trajecgenerator::removeTrajecHandlerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct removeTrajecHandlerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::trajecgenerator::removeTrajecHandlerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::trajecgenerator::removeTrajecHandlerResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TRAJECGENERATOR_MESSAGE_REMOVETRAJECHANDLERRESPONSE_H
